using ARM_Engineer.Database;
using Npgsql;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace ARM_Engineer.Approval_status
{
    public partial class Approval_status_Windows : Window
    {
        List<Approval_status> list;
        public Approval_status_Windows()
        {
            this.WindowStartupLocation = System.Windows.WindowStartupLocation.CenterScreen;
            InitializeComponent();
            Data_output();
        }
        void Data_output()
        {
            list = new List<Approval_status>();
            NpgsqlCommand npgc = new NpgsqlCommand("SELECT * FROM public.\"Approval_status\"", DataBase.Connection());
            NpgsqlDataReader reader = npgc.ExecuteReader();
            if (reader.HasRows)//Если пришли результаты
            {
                while (reader.Read())//Считывает строчку
                {
                    list.Add(new Approval_status());
                    list.Last().ID = reader.GetInt32(0);
                    list.Last().Name = reader.GetString(1);
                    if (reader.IsDBNull(2))
                    {
                        list.Last().Description = null;
                    }
                    else
                    {
                        list.Last().Description = reader.GetString(2);
                    }

                }
                dataGrid_Approval_status.ItemsSource = list;
            }
        }
        private void dataGrid_Approval_status_SelectionChanged(object sender, SelectionChangedEventArgs e) { }
        private void dataGrid_Approval_status_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid_Approval_status.Columns[0].Visibility = Visibility.Collapsed;
            dataGrid_Approval_status.Columns[1].Header = "Name";
            dataGrid_Approval_status.Columns[2].Header = "Description";
        }
        private void button_Add_Click(object sender, RoutedEventArgs e)
        {
            Approval_status_add approval_Status_Add = new Approval_status_add("Добавить", null);
            approval_Status_Add.Title = "Статус согласование(Добавить)";
            approval_Status_Add.ShowDialog();

            if (approval_Status_Add.DialogResult == true)
            {
                Data_output();
            }

        }
        private void Change_ContextMenu(object sender, RoutedEventArgs e)
        {
            if (dataGrid_Approval_status.SelectedItems.Count == 1)
            {
                Approval_status_add approval_Status_Add = new Approval_status_add("Изменить", (Approval_status)dataGrid_Approval_status.SelectedItems[0]);
                approval_Status_Add.Title = "Статус согласование(Изменить)";
                approval_Status_Add.ShowDialog();
                if (approval_Status_Add.DialogResult == true)
                {
                    Data_output();
                }
            }
        }
        private void Remove_ContextMenu(object sender, RoutedEventArgs e)
        {
            if (MessageBox.Show("Вы действительно хотите удалить данную строку?", "Уведомление", MessageBoxButton.YesNoCancel, MessageBoxImage.Question) == MessageBoxResult.Yes)
            {
                Approval_status request = dataGrid_Approval_status.SelectedItem as Approval_status;
                string commandText = $"DELETE FROM \"Approval_status\" WHERE \"ID\"=(@p)";
                using (var cmd = new NpgsqlCommand(commandText, DataBase.Connection()))
                {
                    cmd.Parameters.AddWithValue("p", request.ID);
                    cmd.ExecuteNonQuery();
                }
                Data_output();
            }
        }

        private void dataGrid_Approval_status_SelectionChanged_1(object sender, SelectionChangedEventArgs e)
        {

        }
    }
}
