using ARM_Engineer.Database;
using Npgsql;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace ARM_Engineer.Approval_status
{
    public partial class Approval_status_Windows : Window
    {
        public Approval_status_Windows()
        {
            InitializeComponent();

            var list = new List<Approval_status>();
            NpgsqlCommand npgc = new NpgsqlCommand("SELECT * FROM public.\"Approval_status\"", DataBaseConnection.Connection());
            NpgsqlDataReader reader = npgc.ExecuteReader();
            if (reader.HasRows)//Если пришли результаты
            {
                while (reader.Read())//Считывает строчку
                {
                    list.Add(new Approval_status());
                    list.Last().ID = reader.GetInt32(0);
                    list.Last().Name = reader.GetString(1);
                    if (reader.IsDBNull(2))
                    {
                        list.Last().Description = null;
                    }
                    else
                    {
                        list.Last().Description = reader.GetString(2);
                    }
                    dataGrid_Approval_status.ItemsSource = list;
                }
            }
        }

        private void dataGrid_Approval_status_SelectionChanged(object sender, SelectionChangedEventArgs e) { }
        private void dataGrid_Approval_status_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid_Approval_status.Columns[0].Visibility = Visibility.Collapsed;
            dataGrid_Approval_status.Columns[1].Header = "Name";
            dataGrid_Approval_status.Columns[2].Header = "Description";
        }

        private void button_Remove_Click(object sender, RoutedEventArgs e)
        {
            //var selectedRow = dataGrid_Approval_status.SelectedItem;
            Approval_status request = dataGrid_Approval_status.SelectedItem as Approval_status;
            string commandText = $"DELETE FROM \"Approval_status\" WHERE \"ID\"=(@p)";
            using (var cmd = new NpgsqlCommand(commandText, DataBaseConnection.Connection()))
            {
                cmd.Parameters.AddWithValue("p", request.ID);
                cmd.ExecuteNonQuery();
                MessageBox.Show("Удаление успешно выполнено", "Уведомление", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            CollectionViewSource.GetDefaultView(dataGrid_Approval_status.ItemsSource).Refresh();
        }

        private void button_Add_Click(object sender, RoutedEventArgs e)
        {
            Approval_status_add approval_Status_Add = new Approval_status_add();
            approval_Status_Add.Show();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            //Button btn = sender as Button;
            //System.Data.DataRowView drv = btn.DataContext as System.Data.DataRowView;
            //drv["last_update"] = DateTime.Now;
            //var selectedRow = dataGrid_Approval_status.SelectedItem;
            //Approval_status request = selectedRow as Approval_status;
            //var commandText = $"UPDATE \"Approval_status\" SET \"Name\" =(@name),\"Description\"=(@minPl) WHERE \"ID\" = (@id)";
            //try
            //{
            //    using (var cmd = new NpgsqlCommand(commandText, DataBaseConnection.Connection()))
            //    {
            //        cmd.Parameters.AddWithValue("id", request.ID);
            //        cmd.Parameters.AddWithValue("name", request.Name);
            //        cmd.Parameters.AddWithValue("minPl", request.Description);
            //        DataTable dataTable = new DataTable();
            //        dataGrid_Approval_status.ItemsSource = dataTable.DefaultView;
            //        cmd.ExecuteNonQuery();
            //    }
            //}
            //catch (Exception ex)
            //{
            //    MessageBox.Show(ex.Message, ex.GetType().ToString(), MessageBoxButton.OK, MessageBoxImage.Error);
            //}
        }

        private void dataGrid_Approval_status_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Approval_status_add approval_Status_Add = new Approval_status_add();

            approval_Status_Add.Showew();
            approval_Status_Add.Title = "Изменение";

            DataGrid dataGrid = (DataGrid)sender;
            DataRowView dataRowView = dataGrid.SelectedItem as DataRowView;
            if(dataRowView != null)
            {
                approval_Status_Add.textBox_Name_Approval_status.Text = dataRowView[Name].ToString();


            }




        }
    }
}
